### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by apoorvagnihotri**
- added B-spline.
- a base class containing `fit` and `predict` so possibly we can reuse docstring across all the interpolation methods.
- [ ] trying out docs, will push once done.
- [x] add trend interpolation

### CODE REVIEW

**Comment by sdeepaknarayanan** [comment]
Change the spelling of dimention to *dimension*. Also, make sure comments and docstrings have as minimal grammatical errors as possible.

**Comment by sdeepaknarayanan** [comment]
Regarding B-Spline, when there are multiple optional arguments, can you mention the argument type as (int, int) or something? kx, ky, as I see it, do not seem to have this. Also add comments mentioning what each variable means. What does "tck" mean for an example? I'll merge once you make the changes

**Comment by sdeepaknarayanan** [comment]
Is there any reason why function definitions are written your way?
The def f(a,
B,
C) with indentation. I’d avoid that as long as there aren’t too many arguments (<6). No issue tho. We can change later

**Comment by nipunbatra** [comment]
We should use Black formatter for the code: https://github.com/python/black

**Comment by apoorvagnihotri** [comment]
Ran the following files and directories with [black](https://github.com/python/black):

```
usage.py
interpolation/trend
interpolation/spline
interpolation/random
interpolation/base
```
@sdeepaknarayanan I haven't run black on your code files as it will cause problems in merging later.

**Pull request merged**
